### ISSUE TITLE
Lab2: Comments

### ISSUE THREAD

**Issue by ringavirda** [DimaBohdan/programming_labs#1]
When you upload code that uses some sort of library (the test files in this case), please add your `package.json` file so anyone can just use their package manager to install dependencies and run the code without trying to figure out what it needs. 
Plus, if you separate files from different labs into different folders than please do that for the first one as well.

**Comment by DimaBohdan** [comment]
Thanks for your advice. I'll definitely fix this problem in the next lab
work.

сб, 19 окт. 2024 г., 15:12 Fallenstar ***@***.***>:
